### ISSUE TITLE
The gettile packet is not recognised by the server

### ISSUE THREAD

**Issue by Ameliorate** [Ameliorate/Buildstation-3#23]
[{"sorter":"GetTile","location":{"level":"default","x":0,"y":0,"z":0}}]
^ That should be valid, but it is not.

**Comment by Ameliorate** [comment]
I just tested this again and now it isn't happening anymore... What?

**Comment by Ameliorate** [comment]
It's happening again...

**Comment by Ameliorate** [comment]
The strange thing is this only happens for the gettile sorter. Nothing else.

**Comment by Ameliorate** [comment]
I KNEW IT!

java.lang.NullPointerException
    at com.ame.bus3.common.packetsorters.PlaceTile.getInnerPacket(PlaceTile.java:55)
    at com.ame.bus3.common.packetsorters.GetTile.sort(GetTile.java:37)
    at com.ame.bus3.common.PacketSorterTracker.sort(PacketSorterTracker.java:67)
    at com.ame.bus3.common.Connection.run(Connection.java:42)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Ameliorate** [comment]
It seems that many tiles are not being properly placed onto the map.
