### ISSUE TITLE
Tile renderer infinitely loops

### ISSUE THREAD

**Issue by Ameliorate** [Ameliorate/Buildstation-3#24]
Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: renderMode is of an invalid or unregistered value: TileRender
    at com.ame.bus3.client.RendererControler.render(RendererControler.java:25)
    at com.ame.bus3.client.BuildstationClientMain.render(BuildstationClientMain.java:35)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:214)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: java.lang.NullPointerException
    at com.ame.bus3.client.TileRenderer.render(TileRenderer.java:56)
    at com.ame.bus3.client.RendererControler.render(RendererControler.java:22)
    ... 3 more

Looking at this, it seems to not actually be the error given, but a different nullpointerexception.
Instead, it apears that the state variable in TileRender.java:56 is null.

**Comment by Ameliorate** [comment]
Partially fixed with 0378f8583886e70024b9bb975eb963790e90d05d, but now it just loops infinitely. I'll try to see if it is failing for a bad reason.

**Comment by Ameliorate** [comment]
Currently throwing and catching this exception:
java.lang.NullPointerException
    at com.ame.bus3.client.TileRenderer.render(TileRenderer.java:48)
    at com.ame.bus3.client.RendererControler.render(RendererControler.java:22)
    at com.ame.bus3.client.BuildstationClientMain.render(BuildstationClientMain.java:33)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:214)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

It was the intended exception, so I don't know what to do.

**Comment by Ameliorate** [comment]
I FOUND IT! Aparently it is placing the tile at 0, 0, 1, but looking for the placed tile at 0, 0, 0. Now to figure out why it is doing that...

**Comment by Ameliorate** [comment]
Places it isn't caused: ~~GetTile~~, PlaceTile, Coordinate.toString, Coordinate.toJSONString

**Comment by Ameliorate** [comment]
The place request in question: {"sorter":"PlaceTile","data":{},"location":{"level":"default","x":0,"y":0,"z":1}
The server thinks it is sending: {"sorter":"PlaceTile","data":{},"location":{"level":"default","x":0,"y":0,"z":0},"type":"Wall"}
However the gettile request is {"sorter":"GetTile","location":{"level":"default","x":0,"y":0,"z":0}}

**Comment by Ameliorate** [comment]
Before a got packet is added the outer packet is:
{"sorter":"PlaceTile","data":{},"location":{"level":"default","x":0,"y":0,"z":0},"type":"Wall"}
After it is:
[{"sorter":"PlaceTile","data":{},"location":{"level":"default","x":0,"y":0,"z":1},"type":"Wall"},{"sorter":"WaitUntill","finished":"got"}]

I think something is wrong with the json library.

**Comment by Ameliorate** [comment]
> location.z++;

^ That is my problem. Aparently it messes with the coordinate variable in a way that causes z 1.

**Comment by Ameliorate** [comment]
Now it infinitely loops at SorterList.waitUntill.wait("got");

**Comment by Ameliorate** [comment]
It appears that get tile isn't sending packets now.
