### ISSUE TITLE
Exception on receiving a packet

### ISSUE THREAD

**Issue by Ameliorate** [Ameliorate/Buildstation-3#9]
Exception in thread "Thread-3" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lorg.json.simple.JSONObject;
    at com.ame.bus3.common.PacketSorterTracker.sort(PacketSorterTracker.java:48)
    at com.ame.bus3.common.PacketSorterTracker.sort(PacketSorterTracker.java:37)
    at com.ame.bus3.common.Connection.run(Connection.java:40)
    at java.lang.Thread.run(Unknown Source)

I don't think I like this json library anymore.

**Comment by Ameliorate** [comment]
Okay it isn't too bad. It just requires a lot of try catch blocks.
